### ISSUE TITLE
Todo - Roadmap

### ISSUE THREAD

**Issue by CinquinAndy** [For-Hives/formenu#5]
- [ ] faire le readme
- [ ] brancher la bonne ci / cd 
- [ ] faire le bon workflow ( comme my-makeup )
- [ ] mettre en place le cypress
- [ ] mettre en place le sitemap
- [ ] brancher le sonar
